export type { PlaceCandidate, PlaceDepth } from './model/types'
export { loadSearchIndex } from './lib/build-search-index'
export { normalizeDistrictText } from './lib/normalize-district'
export { useGeocodePlace } from './api/use-geocode-place'
export type { FavoritePlace } from './model/favorite-place'
export { useFavorites } from './lib/use-favorites'
