export type { PlaceCandidate, PlaceDepth } from './model/types'
export { loadSearchIndex } from './lib/build-search-index'
export { normalizeDistrictText } from './lib/normalize-district'
export { useGeocodePlace } from './api/use-geocode-place'
export { formatKoreanPlaceName } from './api/reverse-geocode'
export { useReverseGeocode } from './api/use-reverse-geocode'
export type { FavoritePlace } from './model/favorite-place'
